# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(590, 752)
        MainWindow.setStyleSheet("QListWidget {\n"
"    background-color: rgb(0, 58, 55);\n"
"    color: rgb(171, 213, 213);\n"
"    border-radius: 15px; /* Задайте радиус, чтобы сделать края овальными */\n"
"    padding: 2px;\n"
"    border: 5px solid rgb(21, 84, 60);\n"
"}\n"
"\n"
"\n"
"/* Стиль вертикального ползунка */\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(21, 84, 60);\n"
"    width: 15px;\n"
"    margin: 20px 0 20px 0;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(171, 213, 213);\n"
"    min-height: 20px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background: rgb(21, 84, 60);\n"
"    height: 20px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"    border-bottom-left-radius: 5px;\n"
"    border-bottom-right-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: rgb(21, 84, 60);\n"
"    height: 20px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"}\n"
"\n"
"/* Убираем стрелки по краям ползунков */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical,\n"
"QScrollBar::left-arrow:horizontal, QScrollBar::right-arrow:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal,\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget{background-color: rgb(0, 58, 55);}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setStyleSheet("#widget{background-color: rgb(0, 58, 55);}")
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setStyleSheet("#widget_2{background-color: rgb(158, 197, 198);\n"
"\n"
"border-radius: 15px; /* Задайте радиус, чтобы сделать края овальными */\n"
"padding: 2px;}")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setMinimumSize(QtCore.QSize(524, 275))
        self.widget_3.setStyleSheet("")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.listWidget = QtWidgets.QListWidget(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(24)
        self.listWidget.setFont(font)
        self.listWidget.setStyleSheet("QListWidget {\n"
"    background-color: rgb(0, 58, 55);\n"
"    color: rgb(171, 213, 213);\n"
"    border-radius: 15px; /* Задайте радиус, чтобы сделать края овальными */\n"
"    padding: 2px;\n"
"    border: 5px solid rgb(21, 84, 60);\n"
"}\n"
"\n"
"\n"
"/* Стиль вертикального ползунка */\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(21, 84, 60);\n"
"    width: 15px;\n"
"    margin: 20px 0 20px 0;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(171, 213, 213);\n"
"    min-height: 20px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background: rgb(21, 84, 60);\n"
"    height: 20px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"    border-bottom-left-radius: 5px;\n"
"    border-bottom-right-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: rgb(21, 84, 60);\n"
"    height: 20px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"}\n"
"\n"
"/* Убираем стрелки по краям ползунков */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical,\n"
"QScrollBar::left-arrow:horizontal, QScrollBar::right-arrow:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal,\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_3.addWidget(self.listWidget)
        self.verticalLayout_4.addWidget(self.widget_3)
        self.label = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(0, 58, 55);")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.horizontalSlider = QtWidgets.QSlider(self.widget_2)
        self.horizontalSlider.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: 1px solid #999999;\n"
"    height: 8px;\n"
"    background: rgb(21, 84, 60);;\n"
"    margin: 2px 0;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: rgb(158, 197, 198);\n"
"    border: 1px solid #5c5c5c;\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 9px;\n"
"    margin: -5px 0; /* handle is placed by default on the contents rect of the groove. Expand outside the groove */\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"    background: #d0d0d0;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background: rgb(21, 84, 60);\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"    background: #b1b1b1;\n"
"    border: 1px solid #3a9ef4;\n"
"}\n"
"\n"
"QSlider::groove:horizontal:hover {\n"
"    background: #c0c0c0;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal:disabled {\n"
"    background: #bbbbbb;\n"
"    border-color: #999999;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal:disabled {\n"
"    background: #e0e0e0;\n"
"    border-color: #999999;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled {\n"
"    background: #cccccc;\n"
"    border: 1px solid #999999;\n"
"}")
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout_4.addWidget(self.horizontalSlider)
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setStyleSheet("#widget_4{background-color: rgb(158, 197, 198);\n"
"\n"
"border-radius: 15px; /* Задайте радиус, чтобы сделать края овальными */\n"
"padding: 2px;\n"
"border: 4px solid rgb(0, 58, 55);\n"
"}")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 4, -1, 7)
        self.verticalLayout.setSpacing(39)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.widget_4)
        self.pushButton.setMinimumSize(QtCore.QSize(500, 50))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(24)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("#pushButton {\n"
"    background-color: rgb(21, 84, 60);\n"
"\n"
"    color: rgb(171, 213, 213);\n"
"border-radius: 15px; /* Задайте радиус, чтобы сделать края овальными */\n"
"padding: 2px;}\n"
"\n"
"\n"
"#pushButton:hover{\n"
"background-color: rgb(24, 100, 71);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_2.setMinimumSize(QtCore.QSize(500, 50))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(24)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("#pushButton_2 {\n"
"    background-color: rgb(21, 84, 60);\n"
"\n"
"    color: rgb(171, 213, 213);\n"
"border-radius: 15px; /* Задайте радиус, чтобы сделать края овальными */\n"
"padding: 2px;}\n"
"\n"
"\n"
"#pushButton:hover{\n"
"background-color: rgb(24, 100, 71);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_3.setMinimumSize(QtCore.QSize(500, 50))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(24)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("#pushButton_3 {\n"
"    background-color: rgb(21, 84, 60);\n"
"\n"
"    color: rgb(171, 213, 213);\n"
"border-radius: 15px; /* Задайте радиус, чтобы сделать края овальными */\n"
"padding: 2px;}\n"
"\n"
"\n"
"#pushButton:hover{\n"
"background-color: rgb(24, 100, 71);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_4.setMinimumSize(QtCore.QSize(500, 50))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(24)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("#pushButton_4 {\n"
"    background-color: rgb(21, 84, 60);\n"
"\n"
"    color: rgb(171, 213, 213);\n"
"border-radius: 15px; /* Задайте радиус, чтобы сделать края овальными */\n"
"padding: 2px;}\n"
"\n"
"\n"
"#pushButton:hover{\n"
"background-color: rgb(24, 100, 71);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_4.addWidget(self.widget_4, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_5.addWidget(self.widget_2)
        self.verticalLayout_6.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "PLAY"))
        self.pushButton_2.setText(_translate("MainWindow", "STOP"))
        self.pushButton_3.setText(_translate("MainWindow", "ADD MUSIC"))
        self.pushButton_4.setText(_translate("MainWindow", "DELETE MUSIC"))
